# Generated by Django 2.2 on 2020-04-24 14:42

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Назва')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Опис')),
                ('meta_keywords', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ключові слова')),
                ('meta_description', models.TextField(blank=True, max_length=100, null=True, verbose_name='Опис сторінки')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='ObjectProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('APARTMENT', 'Квартира'), ('HOUSE', 'Будинок'), ('LAND_PLOT', 'Земельна ділянка'), ('COTTAGE', 'Дачний масив')], max_length=50, verbose_name="Тип Об'єкту")),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Опис')),
                ('meta_keywords', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ключові слова')),
                ('meta_description', models.TextField(blank=True, max_length=100, null=True, verbose_name='Опис сторінки')),
                ('locality', models.CharField(max_length=50, verbose_name='Населенный пункт')),
                ('area', models.CharField(max_length=50, verbose_name='Район/Массив')),
                ('street', models.CharField(max_length=50, verbose_name='Вулиця')),
                ('rooms', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Кімнат')),
                ('space', models.IntegerField(verbose_name='Площа')),
                ('price', models.FloatField(verbose_name='Ціна')),
                ('published', models.DateField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='property.Category', verbose_name='Категорія')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_object_tottal', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': "Об'єкт",
                'verbose_name_plural': "Об'єкти",
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='ObjectPropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_object', to=settings.FILER_IMAGE_MODEL)),
                ('object_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.ObjectProperty', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Зображення',
                'verbose_name_plural': 'Додаткові зображення',
            },
        ),
    ]
