# Generated by Django 2.2 on 2020-04-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectproperty',
            old_name='category',
            new_name='category_object',
        ),
    ]
