# Generated by Django 3.0.5 on 2020-04-25 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('property', '0002_auto_20200424_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings_site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Назва')),
                ('meta_keywords', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ключові слова')),
                ('meta_description', models.TextField(blank=True, max_length=100, null=True, verbose_name='Опис сторінки')),
                ('phone_1', models.CharField(max_length=30, verbose_name='Назва')),
                ('pthon_2', models.CharField(max_length=30, verbose_name='Назва')),
                ('link_facebook', models.CharField(max_length=50, verbose_name='Посилання Facebook')),
                ('link_instagram', models.CharField(max_length=50, verbose_name='Посилання Instagram')),
                ('link_telegram', models.CharField(max_length=50, verbose_name='Посилання Telegram')),
                ('site_image_title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('site_image_description', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('favicon', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favicon', to=settings.FILER_IMAGE_MODEL)),
                ('site_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_image', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
    ]
