# Generated by Django 3.0.5 on 2020-04-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20200428_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='pthon_2',
            field=models.CharField(max_length=30, verbose_name='Телефон №2'),
        ),
    ]
