# Generated by Django 3.0.5 on 2020-04-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20200428_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='site_image_title',
            new_name='site_image_text_1',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='site_image_description',
            new_name='site_image_text_2',
        ),
    ]
