# Generated by Django 3.0.5 on 2020-05-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20200428_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='pthon_2',
            new_name='phone_2',
        ),
    ]
