# Generated by Django 3.0.5 on 2020-05-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20200504_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='objectproperty',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='site_image_text_1',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='site_image_text_2',
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Мета заголовок'),
        ),
        migrations.AddField(
            model_name='objectproperty',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Мета заголовок'),
        ),
        migrations.AddField(
            model_name='setting',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Мета заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='objectproperty',
            name='meta_description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Мета опис'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='meta_description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Мета опис'),
        ),
    ]
