# Generated by Django 3.0.5 on 2020-05-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20200511_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Налаштування', 'verbose_name_plural': 'Налаштування'},
        ),
        migrations.AlterField(
            model_name='objectproperty',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
    ]
