# Generated by Django 3.0.5 on 2020-05-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20200514_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectproperty',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендований'),
        ),
    ]
