# Generated by Django 3.0.5 on 2020-05-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_objectproperty_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectPropertyOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('APARTMENT', 'Квартира'), ('HOUSE', 'Будинок'), ('LAND_PLOT', 'Земельна ділянка'), ('COTTAGE', 'Дачний масив')], max_length=50, verbose_name='Опція')),
                ('object_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='property.ObjectProperty', verbose_name='Опція')),
            ],
            options={
                'verbose_name': 'Опція',
                'verbose_name_plural': 'Опції',
            },
        ),
    ]
