# Generated by Django 3.0.5 on 2020-05-15 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_objectpropertyoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectpropertyoption',
            name='option',
        ),
        migrations.AddField(
            model_name='objectpropertyoption',
            name='name',
            field=models.CharField(choices=[('APARTMENT', 'Квартира'), ('HOUSE', 'Будинок'), ('LAND_PLOT', 'Земельна ділянка'), ('COTTAGE', 'Дачний масив')], default=django.utils.timezone.now, max_length=50, verbose_name='Назва'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectpropertyoption',
            name='value',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Значення'),
            preserve_default=False,
        ),
    ]
