# Generated by Django 3.0.5 on 2020-05-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20200515_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectPropertyOption',
        ),
    ]
