# Generated by Django 3.0.5 on 2020-05-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_delete_objectpropertyoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectproperty',
            name='space',
        ),
        migrations.AddField(
            model_name='objectproperty',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Поверх'),
        ),
        migrations.AddField(
            model_name='objectproperty',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Висота стелі'),
        ),
        migrations.AddField(
            model_name='objectproperty',
            name='kitchen_space',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кухня площа'),
        ),
        migrations.AddField(
            model_name='objectproperty',
            name='living_space',
            field=models.IntegerField(blank=True, null=True, verbose_name='Житлова площа'),
        ),
        migrations.AddField(
            model_name='objectproperty',
            name='storeys',
            field=models.IntegerField(blank=True, null=True, verbose_name='Поверховість'),
        ),
        migrations.AddField(
            model_name='objectproperty',
            name='total_space',
            field=models.IntegerField(blank=True, null=True, verbose_name='Загальна площа'),
        ),
        migrations.AlterField(
            model_name='objectproperty',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Район/Массив'),
        ),
        migrations.AlterField(
            model_name='objectproperty',
            name='object_type',
            field=models.CharField(choices=[('Квартира', 'Квартира'), ('Будинок', 'Будинок'), ('Земельна ділянка', 'Земельна ділянка'), ('Дачний масив', 'Дачний масив')], max_length=50, verbose_name="Тип Об'єкту"),
        ),
        migrations.AlterField(
            model_name='objectproperty',
            name='rooms',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Кількість кімнат'),
        ),
        migrations.AlterField(
            model_name='objectproperty',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вулиця'),
        ),
        migrations.AlterField(
            model_name='objectproperty',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Назва'),
        ),
    ]
