# Generated by Django 3.0.5 on 2020-05-15 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('property', '0021_auto_20200515_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectproperty',
            name='floor',
            field=models.FloatField(blank=True, null=True, verbose_name='Поверх'),
        ),
        migrations.AlterField(
            model_name='objectproperty',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Висота стелі'),
        ),
        migrations.AlterField(
            model_name='objectproperty',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_object_tottal', to=settings.FILER_IMAGE_MODEL, verbose_name='Головне зображення'),
        ),
        migrations.AlterField(
            model_name='objectproperty',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160, null=True, verbose_name='Мета опис'),
        ),
    ]
