# Generated by Django 3.0.5 on 2020-05-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20200515_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectproperty',
            name='object_type',
            field=models.CharField(choices=[('Квартира', 'Квартира'), ('Будинок', 'Будинок'), ('Земельна ділянка', 'Земельна ділянка'), ('Дачний масив', 'Дачний масив'), ('Комерційна нерухомість', 'Комерційна нерухомість')], max_length=50, verbose_name="Тип Об'єкту"),
        ),
    ]
