# Generated by Django 3.0.5 on 2020-05-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_auto_20200516_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectproperty',
            name='rooms',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Кількість кімнат'),
        ),
    ]
