# Generated by Django 3.0.5 on 2020-05-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_auto_20200516_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectproperty',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Поверх'),
        ),
    ]
