# Generated by Django 3.0.5 on 2020-05-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_auto_20200526_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='base_url',
            field=models.TextField(default=1, max_length=50, verbose_name='Головне посилання'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Заголовок'),
        ),
    ]
