# Generated by Django 3.0.5 on 2020-05-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_auto_20200526_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='base_url',
            field=models.CharField(max_length=50, verbose_name='Головне посилання'),
        ),
    ]
