# Generated by Django 3.0 on 2021-06-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0031_auto_20200707_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='footer',
        ),
        migrations.AddField(
            model_name='page',
            name='about_as',
            field=models.BooleanField(default=False, verbose_name='Підвал (Про нас)'),
        ),
        migrations.AddField(
            model_name='page',
            name='information',
            field=models.BooleanField(default=False, verbose_name='Підвал (Інформація)'),
        ),
    ]
